# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-25 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
