# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-26 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200325_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default=85.99, max_digits=6),
            preserve_default=False,
        ),
    ]
